// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: user/v1/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role - Foydalanuvchi rollari
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1 // Oddiy foydalanuvchi
	Role_ROLE_ADMIN       Role = 2 // Administrator
	Role_ROLE_SUPER_ADMIN Role = 3 // Super administrator
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
		3: "ROLE_SUPER_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
		"ROLE_SUPER_ADMIN": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// Permission - Tizim ruxsatlari (RBAC uchun)
type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED Permission = 0
	// User permissions (1-9)
	Permission_PERMISSION_VIEW_TOURNAMENTS    Permission = 1
	Permission_PERMISSION_REGISTER_TOURNAMENT Permission = 2
	Permission_PERMISSION_VIEW_PROFILE        Permission = 3
	// Admin permissions (10-19)
	Permission_PERMISSION_CREATE_TOURNAMENT Permission = 10
	Permission_PERMISSION_UPDATE_TOURNAMENT Permission = 11
	Permission_PERMISSION_DELETE_TOURNAMENT Permission = 12
	Permission_PERMISSION_MANAGE_USERS      Permission = 13
	// Super admin permissions (20+)
	Permission_PERMISSION_MANAGE_ADMINS   Permission = 20
	Permission_PERMISSION_SYSTEM_SETTINGS Permission = 21
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "PERMISSION_UNSPECIFIED",
		1:  "PERMISSION_VIEW_TOURNAMENTS",
		2:  "PERMISSION_REGISTER_TOURNAMENT",
		3:  "PERMISSION_VIEW_PROFILE",
		10: "PERMISSION_CREATE_TOURNAMENT",
		11: "PERMISSION_UPDATE_TOURNAMENT",
		12: "PERMISSION_DELETE_TOURNAMENT",
		13: "PERMISSION_MANAGE_USERS",
		20: "PERMISSION_MANAGE_ADMINS",
		21: "PERMISSION_SYSTEM_SETTINGS",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED":         0,
		"PERMISSION_VIEW_TOURNAMENTS":    1,
		"PERMISSION_REGISTER_TOURNAMENT": 2,
		"PERMISSION_VIEW_PROFILE":        3,
		"PERMISSION_CREATE_TOURNAMENT":   10,
		"PERMISSION_UPDATE_TOURNAMENT":   11,
		"PERMISSION_DELETE_TOURNAMENT":   12,
		"PERMISSION_MANAGE_USERS":        13,
		"PERMISSION_MANAGE_ADMINS":       20,
		"PERMISSION_SYSTEM_SETTINGS":     21,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[1].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[1]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

// User - Asosiy foydalanuvchi modeli
type User struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique ID
	TelegramId int64                  `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"` // Telegram user ID
	Username   string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                        // Telegram username (@username)
	FirstName  string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`     // Ism
	LastName   string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`        // Familiya
	Phone      string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                              // Telefon raqami
	Role       Role                   `protobuf:"varint,7,opt,name=role,proto3,enum=Role" json:"role,omitempty"`                     // Foydalanuvchi roli
	// Stats
	Rating            int32                  `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`                                                 // ELO rating (default: 1000)
	RatingPeak        int32                  `protobuf:"varint,9,opt,name=rating_peak,json=ratingPeak,proto3" json:"rating_peak,omitempty"`                       // Eng yuqori rating (all-time)
	GamesPlayed       int32                  `protobuf:"varint,10,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`                   // O'ynagan o'yinlar soni
	GamesWon          int32                  `protobuf:"varint,11,opt,name=games_won,json=gamesWon,proto3" json:"games_won,omitempty"`                            // Yutgan o'yinlar
	GamesLost         int32                  `protobuf:"varint,12,opt,name=games_lost,json=gamesLost,proto3" json:"games_lost,omitempty"`                         // Yutqazgan o'yinlar
	TournamentsPlayed int32                  `protobuf:"varint,13,opt,name=tournaments_played,json=tournamentsPlayed,proto3" json:"tournaments_played,omitempty"` // Turnirlar soni
	TournamentsWon    int32                  `protobuf:"varint,14,opt,name=tournaments_won,json=tournamentsWon,proto3" json:"tournaments_won,omitempty"`          // Yutgan turnirlar
	CurrentStreak     int32                  `protobuf:"varint,15,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`             // Hozirgi g'alaba seriyasi
	BestStreak        int32                  `protobuf:"varint,16,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`                      // Eng yaxshi seriya
	IsActive          bool                   `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                            // Aktiv/deaktiv
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSeenAt        *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *User) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *User) GetRatingPeak() int32 {
	if x != nil {
		return x.RatingPeak
	}
	return 0
}

func (x *User) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *User) GetGamesWon() int32 {
	if x != nil {
		return x.GamesWon
	}
	return 0
}

func (x *User) GetGamesLost() int32 {
	if x != nil {
		return x.GamesLost
	}
	return 0
}

func (x *User) GetTournamentsPlayed() int32 {
	if x != nil {
		return x.TournamentsPlayed
	}
	return 0
}

func (x *User) GetTournamentsWon() int32 {
	if x != nil {
		return x.TournamentsWon
	}
	return 0
}

func (x *User) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *User) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

// UserStats - Batafsil statistika
type UserStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating            int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	RatingPeak        int32                  `protobuf:"varint,3,opt,name=rating_peak,json=ratingPeak,proto3" json:"rating_peak,omitempty"`
	GamesPlayed       int32                  `protobuf:"varint,4,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	GamesWon          int32                  `protobuf:"varint,5,opt,name=games_won,json=gamesWon,proto3" json:"games_won,omitempty"`
	GamesLost         int32                  `protobuf:"varint,6,opt,name=games_lost,json=gamesLost,proto3" json:"games_lost,omitempty"`
	WinRate           float64                `protobuf:"fixed64,7,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"` // Yutish foizi (0.0 - 1.0)
	TournamentsPlayed int32                  `protobuf:"varint,8,opt,name=tournaments_played,json=tournamentsPlayed,proto3" json:"tournaments_played,omitempty"`
	TournamentsWon    int32                  `protobuf:"varint,9,opt,name=tournaments_won,json=tournamentsWon,proto3" json:"tournaments_won,omitempty"`
	CurrentStreak     int32                  `protobuf:"varint,10,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	BestStreak        int32                  `protobuf:"varint,11,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserStats) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStats) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UserStats) GetRatingPeak() int32 {
	if x != nil {
		return x.RatingPeak
	}
	return 0
}

func (x *UserStats) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *UserStats) GetGamesWon() int32 {
	if x != nil {
		return x.GamesWon
	}
	return 0
}

func (x *UserStats) GetGamesLost() int32 {
	if x != nil {
		return x.GamesLost
	}
	return 0
}

func (x *UserStats) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *UserStats) GetTournamentsPlayed() int32 {
	if x != nil {
		return x.TournamentsPlayed
	}
	return 0
}

func (x *UserStats) GetTournamentsWon() int32 {
	if x != nil {
		return x.TournamentsWon
	}
	return 0
}

func (x *UserStats) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *UserStats) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

// LeaderboardEntry - Reytinglar ro'yxati elementi
type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                       // O'rin (1, 2, 3...)
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`                        // Foydalanuvchi ma'lumotlari
	WinRate       float64                `protobuf:"fixed64,3,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"` // Yutish foizi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LeaderboardEntry) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                   // JWT access token
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // "Welcome!" yoki "Welcome back!"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserByTelegramIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTelegramIDRequest) Reset() {
	*x = GetUserByTelegramIDRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIDRequest) ProtoMessage() {}

func (x *GetUserByTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByTelegramIDRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

type UpdateUserRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional fields - faqat o'zgartiriladigan fieldlar
	FirstName     *string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Phone         *string `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Username      *string `protobuf:"bytes,5,opt,name=username,proto3,oneof" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // O'chirish sababi (audit log uchun)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                               // Sahifa raqami (1 dan boshlanadi)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                       // Har sahifada nechta (default: 20)
	RoleFilter    *Role                  `protobuf:"varint,3,opt,name=role_filter,json=roleFilter,proto3,enum=Role,oneof" json:"role_filter,omitempty"` // Role bo'yicha filter
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`                                      // Username/name bo'yicha qidirish
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUsersRequest) GetRoleFilter() Role {
	if x != nil && x.RoleFilter != nil {
		return *x.RoleFilter
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GetUsersRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                             // Jami foydalanuvchilar soni
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // Hozirgi sahifa
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // Sahifa hajmi
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // Jami sahifalar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUsersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type UpdateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RatingChange  int32                  `protobuf:"varint,2,opt,name=rating_change,json=ratingChange,proto3" json:"rating_change,omitempty"` // +10 yoki -10
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                  // "Won match vs User#123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatingRequest) Reset() {
	*x = UpdateRatingRequest{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingRequest) ProtoMessage() {}

func (x *UpdateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateRatingRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRatingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateRatingRequest) GetRatingChange() int32 {
	if x != nil {
		return x.RatingChange
	}
	return 0
}

func (x *UpdateRatingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // TOP nechta (default: 10)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Pagination uchun
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TelegramId    int64                  `protobuf:"varint,3,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Agar valid=false bo'lsa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResponse) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *ValidateTokenResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permission    Permission             `protobuf:"varint,2,opt,name=permission,proto3,enum=Permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *CheckPermissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermissionRequest) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Agar yo'q bo'lsa, sababi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *CheckPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

func (x *CheckPermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MakeAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // Kimni admin qilish
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`           // Kim admin qilyapti
	NewRole       Role                   `protobuf:"varint,3,opt,name=new_role,json=newRole,proto3,enum=Role" json:"new_role,omitempty"` // Yangi rol
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                             // Sabab (audit log)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminRequest) Reset() {
	*x = MakeAdminRequest{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminRequest) ProtoMessage() {}

func (x *MakeAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminRequest.ProtoReflect.Descriptor instead.
func (*MakeAdminRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *MakeAdminRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MakeAdminRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *MakeAdminRequest) GetNewRole() Role {
	if x != nil {
		return x.NewRole
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *MakeAdminRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ErrorResponse - Xatolik uchun (gRPC status details da)
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                 // "USER_NOT_FOUND", "INVALID_TOKEN"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // "User with ID 123 not found"
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Qo'shimcha ma'lumotlar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc9\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\x03R\n" +
	"telegramId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x19\n" +
	"\x04role\x18\a \x01(\x0e2\x05.RoleR\x04role\x12\x16\n" +
	"\x06rating\x18\b \x01(\x05R\x06rating\x12\x1f\n" +
	"\vrating_peak\x18\t \x01(\x05R\n" +
	"ratingPeak\x12!\n" +
	"\fgames_played\x18\n" +
	" \x01(\x05R\vgamesPlayed\x12\x1b\n" +
	"\tgames_won\x18\v \x01(\x05R\bgamesWon\x12\x1d\n" +
	"\n" +
	"games_lost\x18\f \x01(\x05R\tgamesLost\x12-\n" +
	"\x12tournaments_played\x18\r \x01(\x05R\x11tournamentsPlayed\x12'\n" +
	"\x0ftournaments_won\x18\x0e \x01(\x05R\x0etournamentsWon\x12%\n" +
	"\x0ecurrent_streak\x18\x0f \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\x10 \x01(\x05R\n" +
	"bestStreak\x12\x1b\n" +
	"\tis_active\x18\x11 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\flast_seen_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xf7\x02\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x1f\n" +
	"\vrating_peak\x18\x03 \x01(\x05R\n" +
	"ratingPeak\x12!\n" +
	"\fgames_played\x18\x04 \x01(\x05R\vgamesPlayed\x12\x1b\n" +
	"\tgames_won\x18\x05 \x01(\x05R\bgamesWon\x12\x1d\n" +
	"\n" +
	"games_lost\x18\x06 \x01(\x05R\tgamesLost\x12\x19\n" +
	"\bwin_rate\x18\a \x01(\x01R\awinRate\x12-\n" +
	"\x12tournaments_played\x18\b \x01(\x05R\x11tournamentsPlayed\x12'\n" +
	"\x0ftournaments_won\x18\t \x01(\x05R\x0etournamentsWon\x12%\n" +
	"\x0ecurrent_streak\x18\n" +
	" \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\v \x01(\x05R\n" +
	"bestStreak\"\\\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x19\n" +
	"\x04user\x18\x02 \x01(\v2\x05.UserR\x04user\x12\x19\n" +
	"\bwin_rate\x18\x03 \x01(\x01R\awinRate\"\xa0\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\"\xbd\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"=\n" +
	"\x1aGetUserByTelegramIDRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\"\xe2\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x02R\x05phone\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x05 \x01(\tH\x03R\busername\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phoneB\v\n" +
	"\t_username\"D\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa7\x01\n" +
	"\x0fGetUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12+\n" +
	"\vrole_filter\x18\x03 \x01(\x0e2\x05.RoleH\x00R\n" +
	"roleFilter\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x01R\x06search\x88\x01\x01B\x0e\n" +
	"\f_role_filterB\t\n" +
	"\a_search\"\x97\x01\n" +
	"\x10GetUsersResponse\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"k\n" +
	"\x13UpdateRatingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rrating_change\x18\x02 \x01(\x05R\fratingChange\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"[\n" +
	"\x16GetLeaderboardResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.LeaderboardEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x98\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtelegram_id\x18\x03 \x01(\x03R\n" +
	"telegramId\x12\x19\n" +
	"\x04role\x18\x04 \x01(\x0e2\x05.RoleR\x04role\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x85\x01\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"^\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12+\n" +
	"\n" +
	"permission\x18\x02 \x01(\x0e2\v.PermissionR\n" +
	"permission\"X\n" +
	"\x17CheckPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x80\x01\n" +
	"\x10MakeAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12 \n" +
	"\bnew_role\x18\x03 \x01(\x0e2\x05.RoleR\anewRole\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xb0\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\adetails\x18\x03 \x03(\v2\x1b.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*Q\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x14\n" +
	"\x10ROLE_SUPER_ADMIN\x10\x03*\xcb\x02\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPERMISSION_VIEW_TOURNAMENTS\x10\x01\x12\"\n" +
	"\x1ePERMISSION_REGISTER_TOURNAMENT\x10\x02\x12\x1b\n" +
	"\x17PERMISSION_VIEW_PROFILE\x10\x03\x12 \n" +
	"\x1cPERMISSION_CREATE_TOURNAMENT\x10\n" +
	"\x12 \n" +
	"\x1cPERMISSION_UPDATE_TOURNAMENT\x10\v\x12 \n" +
	"\x1cPERMISSION_DELETE_TOURNAMENT\x10\f\x12\x1b\n" +
	"\x17PERMISSION_MANAGE_USERS\x10\r\x12\x1c\n" +
	"\x18PERMISSION_MANAGE_ADMINS\x10\x14\x12\x1e\n" +
	"\x1aPERMISSION_SYSTEM_SETTINGS\x10\x152\xb0\x05\n" +
	"\vUserService\x12/\n" +
	"\bRegister\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12!\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x05.User\x129\n" +
	"\x13GetUserByTelegramID\x12\x1b.GetUserByTelegramIDRequest\x1a\x05.User\x12'\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x05.User\x128\n" +
	"\n" +
	"DeleteUser\x12\x12.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12/\n" +
	"\bGetUsers\x12\x10.GetUsersRequest\x1a\x11.GetUsersResponse\x12+\n" +
	"\fUpdateRating\x12\x14.UpdateRatingRequest\x1a\x05.User\x12A\n" +
	"\x0eGetLeaderboard\x12\x16.GetLeaderboardRequest\x1a\x17.GetLeaderboardResponse\x12+\n" +
	"\fGetUserStats\x12\x0f.GetUserRequest\x1a\n" +
	".UserStats\x12>\n" +
	"\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x16.ValidateTokenResponse\x124\n" +
	"\fRefreshToken\x12\x14.RefreshTokenRequest\x1a\x0e.TokenResponse\x12D\n" +
	"\x0fCheckPermission\x12\x17.CheckPermissionRequest\x1a\x18.CheckPermissionResponse\x12%\n" +
	"\tMakeAdmin\x12\x11.MakeAdminRequest\x1a\x05.UserB\x12Z\x10./user/v1;userpbb\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_user_v1_user_proto_goTypes = []any{
	(Role)(0),                          // 0: Role
	(Permission)(0),                    // 1: Permission
	(*User)(nil),                       // 2: User
	(*UserStats)(nil),                  // 3: UserStats
	(*LeaderboardEntry)(nil),           // 4: LeaderboardEntry
	(*RegisterRequest)(nil),            // 5: RegisterRequest
	(*RegisterResponse)(nil),           // 6: RegisterResponse
	(*GetUserRequest)(nil),             // 7: GetUserRequest
	(*GetUserByTelegramIDRequest)(nil), // 8: GetUserByTelegramIDRequest
	(*UpdateUserRequest)(nil),          // 9: UpdateUserRequest
	(*DeleteUserRequest)(nil),          // 10: DeleteUserRequest
	(*GetUsersRequest)(nil),            // 11: GetUsersRequest
	(*GetUsersResponse)(nil),           // 12: GetUsersResponse
	(*UpdateRatingRequest)(nil),        // 13: UpdateRatingRequest
	(*GetLeaderboardRequest)(nil),      // 14: GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),     // 15: GetLeaderboardResponse
	(*ValidateTokenRequest)(nil),       // 16: ValidateTokenRequest
	(*ValidateTokenResponse)(nil),      // 17: ValidateTokenResponse
	(*RefreshTokenRequest)(nil),        // 18: RefreshTokenRequest
	(*TokenResponse)(nil),              // 19: TokenResponse
	(*CheckPermissionRequest)(nil),     // 20: CheckPermissionRequest
	(*CheckPermissionResponse)(nil),    // 21: CheckPermissionResponse
	(*MakeAdminRequest)(nil),           // 22: MakeAdminRequest
	(*ErrorResponse)(nil),              // 23: ErrorResponse
	nil,                                // 24: ErrorResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 26: google.protobuf.Empty
}
var file_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: User.role:type_name -> Role
	25, // 1: User.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: User.updated_at:type_name -> google.protobuf.Timestamp
	25, // 3: User.last_seen_at:type_name -> google.protobuf.Timestamp
	2,  // 4: LeaderboardEntry.user:type_name -> User
	2,  // 5: RegisterResponse.user:type_name -> User
	25, // 6: RegisterResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: GetUsersRequest.role_filter:type_name -> Role
	2,  // 8: GetUsersResponse.users:type_name -> User
	4,  // 9: GetLeaderboardResponse.entries:type_name -> LeaderboardEntry
	0,  // 10: ValidateTokenResponse.role:type_name -> Role
	25, // 11: TokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 12: CheckPermissionRequest.permission:type_name -> Permission
	0,  // 13: MakeAdminRequest.new_role:type_name -> Role
	24, // 14: ErrorResponse.details:type_name -> ErrorResponse.DetailsEntry
	5,  // 15: UserService.Register:input_type -> RegisterRequest
	7,  // 16: UserService.GetUser:input_type -> GetUserRequest
	8,  // 17: UserService.GetUserByTelegramID:input_type -> GetUserByTelegramIDRequest
	9,  // 18: UserService.UpdateUser:input_type -> UpdateUserRequest
	10, // 19: UserService.DeleteUser:input_type -> DeleteUserRequest
	11, // 20: UserService.GetUsers:input_type -> GetUsersRequest
	13, // 21: UserService.UpdateRating:input_type -> UpdateRatingRequest
	14, // 22: UserService.GetLeaderboard:input_type -> GetLeaderboardRequest
	7,  // 23: UserService.GetUserStats:input_type -> GetUserRequest
	16, // 24: UserService.ValidateToken:input_type -> ValidateTokenRequest
	18, // 25: UserService.RefreshToken:input_type -> RefreshTokenRequest
	20, // 26: UserService.CheckPermission:input_type -> CheckPermissionRequest
	22, // 27: UserService.MakeAdmin:input_type -> MakeAdminRequest
	6,  // 28: UserService.Register:output_type -> RegisterResponse
	2,  // 29: UserService.GetUser:output_type -> User
	2,  // 30: UserService.GetUserByTelegramID:output_type -> User
	2,  // 31: UserService.UpdateUser:output_type -> User
	26, // 32: UserService.DeleteUser:output_type -> google.protobuf.Empty
	12, // 33: UserService.GetUsers:output_type -> GetUsersResponse
	2,  // 34: UserService.UpdateRating:output_type -> User
	15, // 35: UserService.GetLeaderboard:output_type -> GetLeaderboardResponse
	3,  // 36: UserService.GetUserStats:output_type -> UserStats
	17, // 37: UserService.ValidateToken:output_type -> ValidateTokenResponse
	19, // 38: UserService.RefreshToken:output_type -> TokenResponse
	21, // 39: UserService.CheckPermission:output_type -> CheckPermissionResponse
	2,  // 40: UserService.MakeAdmin:output_type -> User
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	file_user_v1_user_proto_msgTypes[7].OneofWrappers = []any{}
	file_user_v1_user_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
