// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: tournament/v1/tournament.proto

package tournamentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TournamentService_CreateTournament_FullMethodName      = "/TournamentService/CreateTournament"
	TournamentService_GetTournament_FullMethodName         = "/TournamentService/GetTournament"
	TournamentService_UpdateTournament_FullMethodName      = "/TournamentService/UpdateTournament"
	TournamentService_DeleteTournament_FullMethodName      = "/TournamentService/DeleteTournament"
	TournamentService_GetTournaments_FullMethodName        = "/TournamentService/GetTournaments"
	TournamentService_StartTournament_FullMethodName       = "/TournamentService/StartTournament"
	TournamentService_EndTournament_FullMethodName         = "/TournamentService/EndTournament"
	TournamentService_CancelTournament_FullMethodName      = "/TournamentService/CancelTournament"
	TournamentService_RegisterParticipant_FullMethodName   = "/TournamentService/RegisterParticipant"
	TournamentService_UnregisterParticipant_FullMethodName = "/TournamentService/UnregisterParticipant"
	TournamentService_GetParticipants_FullMethodName       = "/TournamentService/GetParticipants"
	TournamentService_GetUserTournaments_FullMethodName    = "/TournamentService/GetUserTournaments"
	TournamentService_CreateMatch_FullMethodName           = "/TournamentService/CreateMatch"
	TournamentService_UpdateMatch_FullMethodName           = "/TournamentService/UpdateMatch"
	TournamentService_ReportMatchResult_FullMethodName     = "/TournamentService/ReportMatchResult"
	TournamentService_GetMatches_FullMethodName            = "/TournamentService/GetMatches"
	TournamentService_GetUserMatches_FullMethodName        = "/TournamentService/GetUserMatches"
	TournamentService_GenerateBracket_FullMethodName       = "/TournamentService/GenerateBracket"
	TournamentService_GetBracket_FullMethodName            = "/TournamentService/GetBracket"
	TournamentService_GetStandings_FullMethodName          = "/TournamentService/GetStandings"
	TournamentService_GetUserStanding_FullMethodName       = "/TournamentService/GetUserStanding"
)

// TournamentServiceClient is the client API for TournamentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TournamentServiceClient interface {
	// CreateTournament creates a new tournament
	CreateTournament(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// GetTournament gets tournament by ID
	GetTournament(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// UpdateTournament updates tournament details
	UpdateTournament(ctx context.Context, in *UpdateTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// DeleteTournament deletes tournament (soft delete)
	DeleteTournament(ctx context.Context, in *DeleteTournamentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetTournaments lists tournaments with filters
	GetTournaments(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error)
	// StartTournament starts a tournament
	StartTournament(ctx context.Context, in *StartTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// EndTournament ends a tournament
	EndTournament(ctx context.Context, in *EndTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// CancelTournament cancels a tournament
	CancelTournament(ctx context.Context, in *CancelTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	// RegisterParticipant registers a user for tournament
	RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*Participant, error)
	// UnregisterParticipant removes user from tournament
	UnregisterParticipant(ctx context.Context, in *UnregisterParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetParticipants gets all participants of a tournament
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	// GetUserTournaments gets tournaments user is registered for
	GetUserTournaments(ctx context.Context, in *GetUserTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error)
	// CreateMatch creates a tournament match
	CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*Match, error)
	// UpdateMatch updates match details
	UpdateMatch(ctx context.Context, in *UpdateMatchRequest, opts ...grpc.CallOption) (*Match, error)
	// ReportMatchResult reports match result
	ReportMatchResult(ctx context.Context, in *ReportMatchResultRequest, opts ...grpc.CallOption) (*Match, error)
	// GetMatches gets matches for a tournament
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error)
	// GetUserMatches gets user's matches
	GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error)
	// GenerateBracket generates tournament bracket
	GenerateBracket(ctx context.Context, in *GenerateBracketRequest, opts ...grpc.CallOption) (*Bracket, error)
	// GetBracket gets tournament bracket
	GetBracket(ctx context.Context, in *GetBracketRequest, opts ...grpc.CallOption) (*Bracket, error)
	// GetStandings gets tournament standings
	GetStandings(ctx context.Context, in *GetStandingsRequest, opts ...grpc.CallOption) (*GetStandingsResponse, error)
	// GetUserStanding gets user's standing in tournament
	GetUserStanding(ctx context.Context, in *GetUserStandingRequest, opts ...grpc.CallOption) (*Standing, error)
}

type tournamentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTournamentServiceClient(cc grpc.ClientConnInterface) TournamentServiceClient {
	return &tournamentServiceClient{cc}
}

func (c *tournamentServiceClient) CreateTournament(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_CreateTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetTournament(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_GetTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) UpdateTournament(ctx context.Context, in *UpdateTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_UpdateTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) DeleteTournament(ctx context.Context, in *DeleteTournamentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TournamentService_DeleteTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetTournaments(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTournamentsResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetTournaments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) StartTournament(ctx context.Context, in *StartTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_StartTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) EndTournament(ctx context.Context, in *EndTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_EndTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) CancelTournament(ctx context.Context, in *CancelTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_CancelTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*Participant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Participant)
	err := c.cc.Invoke(ctx, TournamentService_RegisterParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) UnregisterParticipant(ctx context.Context, in *UnregisterParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TournamentService_UnregisterParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantsResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetUserTournaments(ctx context.Context, in *GetUserTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTournamentsResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetUserTournaments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*Match, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Match)
	err := c.cc.Invoke(ctx, TournamentService_CreateMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) UpdateMatch(ctx context.Context, in *UpdateMatchRequest, opts ...grpc.CallOption) (*Match, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Match)
	err := c.cc.Invoke(ctx, TournamentService_UpdateMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) ReportMatchResult(ctx context.Context, in *ReportMatchResultRequest, opts ...grpc.CallOption) (*Match, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Match)
	err := c.cc.Invoke(ctx, TournamentService_ReportMatchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchesResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchesResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetUserMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GenerateBracket(ctx context.Context, in *GenerateBracketRequest, opts ...grpc.CallOption) (*Bracket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bracket)
	err := c.cc.Invoke(ctx, TournamentService_GenerateBracket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetBracket(ctx context.Context, in *GetBracketRequest, opts ...grpc.CallOption) (*Bracket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bracket)
	err := c.cc.Invoke(ctx, TournamentService_GetBracket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetStandings(ctx context.Context, in *GetStandingsRequest, opts ...grpc.CallOption) (*GetStandingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStandingsResponse)
	err := c.cc.Invoke(ctx, TournamentService_GetStandings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetUserStanding(ctx context.Context, in *GetUserStandingRequest, opts ...grpc.CallOption) (*Standing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Standing)
	err := c.cc.Invoke(ctx, TournamentService_GetUserStanding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TournamentServiceServer is the server API for TournamentService service.
// All implementations must embed UnimplementedTournamentServiceServer
// for forward compatibility.
type TournamentServiceServer interface {
	// CreateTournament creates a new tournament
	CreateTournament(context.Context, *CreateTournamentRequest) (*Tournament, error)
	// GetTournament gets tournament by ID
	GetTournament(context.Context, *GetTournamentRequest) (*Tournament, error)
	// UpdateTournament updates tournament details
	UpdateTournament(context.Context, *UpdateTournamentRequest) (*Tournament, error)
	// DeleteTournament deletes tournament (soft delete)
	DeleteTournament(context.Context, *DeleteTournamentRequest) (*emptypb.Empty, error)
	// GetTournaments lists tournaments with filters
	GetTournaments(context.Context, *GetTournamentsRequest) (*GetTournamentsResponse, error)
	// StartTournament starts a tournament
	StartTournament(context.Context, *StartTournamentRequest) (*Tournament, error)
	// EndTournament ends a tournament
	EndTournament(context.Context, *EndTournamentRequest) (*Tournament, error)
	// CancelTournament cancels a tournament
	CancelTournament(context.Context, *CancelTournamentRequest) (*Tournament, error)
	// RegisterParticipant registers a user for tournament
	RegisterParticipant(context.Context, *RegisterParticipantRequest) (*Participant, error)
	// UnregisterParticipant removes user from tournament
	UnregisterParticipant(context.Context, *UnregisterParticipantRequest) (*emptypb.Empty, error)
	// GetParticipants gets all participants of a tournament
	GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error)
	// GetUserTournaments gets tournaments user is registered for
	GetUserTournaments(context.Context, *GetUserTournamentsRequest) (*GetTournamentsResponse, error)
	// CreateMatch creates a tournament match
	CreateMatch(context.Context, *CreateMatchRequest) (*Match, error)
	// UpdateMatch updates match details
	UpdateMatch(context.Context, *UpdateMatchRequest) (*Match, error)
	// ReportMatchResult reports match result
	ReportMatchResult(context.Context, *ReportMatchResultRequest) (*Match, error)
	// GetMatches gets matches for a tournament
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error)
	// GetUserMatches gets user's matches
	GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetMatchesResponse, error)
	// GenerateBracket generates tournament bracket
	GenerateBracket(context.Context, *GenerateBracketRequest) (*Bracket, error)
	// GetBracket gets tournament bracket
	GetBracket(context.Context, *GetBracketRequest) (*Bracket, error)
	// GetStandings gets tournament standings
	GetStandings(context.Context, *GetStandingsRequest) (*GetStandingsResponse, error)
	// GetUserStanding gets user's standing in tournament
	GetUserStanding(context.Context, *GetUserStandingRequest) (*Standing, error)
	mustEmbedUnimplementedTournamentServiceServer()
}

// UnimplementedTournamentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTournamentServiceServer struct{}

func (UnimplementedTournamentServiceServer) CreateTournament(context.Context, *CreateTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTournament not implemented")
}
func (UnimplementedTournamentServiceServer) GetTournament(context.Context, *GetTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTournament not implemented")
}
func (UnimplementedTournamentServiceServer) UpdateTournament(context.Context, *UpdateTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTournament not implemented")
}
func (UnimplementedTournamentServiceServer) DeleteTournament(context.Context, *DeleteTournamentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTournament not implemented")
}
func (UnimplementedTournamentServiceServer) GetTournaments(context.Context, *GetTournamentsRequest) (*GetTournamentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTournaments not implemented")
}
func (UnimplementedTournamentServiceServer) StartTournament(context.Context, *StartTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTournament not implemented")
}
func (UnimplementedTournamentServiceServer) EndTournament(context.Context, *EndTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method EndTournament not implemented")
}
func (UnimplementedTournamentServiceServer) CancelTournament(context.Context, *CancelTournamentRequest) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTournament not implemented")
}
func (UnimplementedTournamentServiceServer) RegisterParticipant(context.Context, *RegisterParticipantRequest) (*Participant, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterParticipant not implemented")
}
func (UnimplementedTournamentServiceServer) UnregisterParticipant(context.Context, *UnregisterParticipantRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterParticipant not implemented")
}
func (UnimplementedTournamentServiceServer) GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipants not implemented")
}
func (UnimplementedTournamentServiceServer) GetUserTournaments(context.Context, *GetUserTournamentsRequest) (*GetTournamentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTournaments not implemented")
}
func (UnimplementedTournamentServiceServer) CreateMatch(context.Context, *CreateMatchRequest) (*Match, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedTournamentServiceServer) UpdateMatch(context.Context, *UpdateMatchRequest) (*Match, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMatch not implemented")
}
func (UnimplementedTournamentServiceServer) ReportMatchResult(context.Context, *ReportMatchResultRequest) (*Match, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMatchResult not implemented")
}
func (UnimplementedTournamentServiceServer) GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatches not implemented")
}
func (UnimplementedTournamentServiceServer) GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMatches not implemented")
}
func (UnimplementedTournamentServiceServer) GenerateBracket(context.Context, *GenerateBracketRequest) (*Bracket, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateBracket not implemented")
}
func (UnimplementedTournamentServiceServer) GetBracket(context.Context, *GetBracketRequest) (*Bracket, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBracket not implemented")
}
func (UnimplementedTournamentServiceServer) GetStandings(context.Context, *GetStandingsRequest) (*GetStandingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStandings not implemented")
}
func (UnimplementedTournamentServiceServer) GetUserStanding(context.Context, *GetUserStandingRequest) (*Standing, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStanding not implemented")
}
func (UnimplementedTournamentServiceServer) mustEmbedUnimplementedTournamentServiceServer() {}
func (UnimplementedTournamentServiceServer) testEmbeddedByValue()                           {}

// UnsafeTournamentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TournamentServiceServer will
// result in compilation errors.
type UnsafeTournamentServiceServer interface {
	mustEmbedUnimplementedTournamentServiceServer()
}

func RegisterTournamentServiceServer(s grpc.ServiceRegistrar, srv TournamentServiceServer) {
	// If the following call panics, it indicates UnimplementedTournamentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TournamentService_ServiceDesc, srv)
}

func _TournamentService_CreateTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).CreateTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_CreateTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).CreateTournament(ctx, req.(*CreateTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetTournament(ctx, req.(*GetTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_UpdateTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).UpdateTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_UpdateTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).UpdateTournament(ctx, req.(*UpdateTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_DeleteTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).DeleteTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_DeleteTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).DeleteTournament(ctx, req.(*DeleteTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetTournaments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetTournaments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetTournaments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetTournaments(ctx, req.(*GetTournamentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_StartTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).StartTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_StartTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).StartTournament(ctx, req.(*StartTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_EndTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).EndTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_EndTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).EndTournament(ctx, req.(*EndTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_CancelTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).CancelTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_CancelTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).CancelTournament(ctx, req.(*CancelTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_RegisterParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).RegisterParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_RegisterParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).RegisterParticipant(ctx, req.(*RegisterParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_UnregisterParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).UnregisterParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_UnregisterParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).UnregisterParticipant(ctx, req.(*UnregisterParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetParticipants(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetUserTournaments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTournamentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetUserTournaments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetUserTournaments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetUserTournaments(ctx, req.(*GetUserTournamentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_CreateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).CreateMatch(ctx, req.(*CreateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_UpdateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).UpdateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_UpdateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).UpdateMatch(ctx, req.(*UpdateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_ReportMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMatchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).ReportMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_ReportMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).ReportMatchResult(ctx, req.(*ReportMatchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetUserMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetUserMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetUserMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetUserMatches(ctx, req.(*GetUserMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GenerateBracket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBracketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GenerateBracket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GenerateBracket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GenerateBracket(ctx, req.(*GenerateBracketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetBracket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBracketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetBracket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetBracket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetBracket(ctx, req.(*GetBracketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetStandings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStandingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetStandings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetStandings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetStandings(ctx, req.(*GetStandingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetUserStanding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStandingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetUserStanding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetUserStanding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetUserStanding(ctx, req.(*GetUserStandingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TournamentService_ServiceDesc is the grpc.ServiceDesc for TournamentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TournamentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TournamentService",
	HandlerType: (*TournamentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTournament",
			Handler:    _TournamentService_CreateTournament_Handler,
		},
		{
			MethodName: "GetTournament",
			Handler:    _TournamentService_GetTournament_Handler,
		},
		{
			MethodName: "UpdateTournament",
			Handler:    _TournamentService_UpdateTournament_Handler,
		},
		{
			MethodName: "DeleteTournament",
			Handler:    _TournamentService_DeleteTournament_Handler,
		},
		{
			MethodName: "GetTournaments",
			Handler:    _TournamentService_GetTournaments_Handler,
		},
		{
			MethodName: "StartTournament",
			Handler:    _TournamentService_StartTournament_Handler,
		},
		{
			MethodName: "EndTournament",
			Handler:    _TournamentService_EndTournament_Handler,
		},
		{
			MethodName: "CancelTournament",
			Handler:    _TournamentService_CancelTournament_Handler,
		},
		{
			MethodName: "RegisterParticipant",
			Handler:    _TournamentService_RegisterParticipant_Handler,
		},
		{
			MethodName: "UnregisterParticipant",
			Handler:    _TournamentService_UnregisterParticipant_Handler,
		},
		{
			MethodName: "GetParticipants",
			Handler:    _TournamentService_GetParticipants_Handler,
		},
		{
			MethodName: "GetUserTournaments",
			Handler:    _TournamentService_GetUserTournaments_Handler,
		},
		{
			MethodName: "CreateMatch",
			Handler:    _TournamentService_CreateMatch_Handler,
		},
		{
			MethodName: "UpdateMatch",
			Handler:    _TournamentService_UpdateMatch_Handler,
		},
		{
			MethodName: "ReportMatchResult",
			Handler:    _TournamentService_ReportMatchResult_Handler,
		},
		{
			MethodName: "GetMatches",
			Handler:    _TournamentService_GetMatches_Handler,
		},
		{
			MethodName: "GetUserMatches",
			Handler:    _TournamentService_GetUserMatches_Handler,
		},
		{
			MethodName: "GenerateBracket",
			Handler:    _TournamentService_GenerateBracket_Handler,
		},
		{
			MethodName: "GetBracket",
			Handler:    _TournamentService_GetBracket_Handler,
		},
		{
			MethodName: "GetStandings",
			Handler:    _TournamentService_GetStandings_Handler,
		},
		{
			MethodName: "GetUserStanding",
			Handler:    _TournamentService_GetUserStanding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tournament/v1/tournament.proto",
}
